services:
    app:
        build: .
        image: virtual-menu-backend
        container_name: virtual-menu-backend
        ports:
            - 8000:80
        environment:
            - URL=192.168.18.3
        depends_on:
            - orders_database
            - general_database
        restart: always
    orders_database:
        image: redis/redis-stack:latest
        container_name: orders_database
        ports:
            - 6379:6379
        restart: always
    general_database:
        image: mongo:6
        container_name: general_database
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=test
            - MONGO_INITDB_DATABASE=restaurants
        restart: always
        volumes:
            - general_database:/data/db
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
    general_database:
